version: "3.7"

services:
  app:
    container_name: app
    build: "."
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network  
    depends_on:
      - postgres
  postgres:
    image: postgres:10.3
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge
volumes:
  postgres:
    external: true